site_name: prefect-openmetadata
repo_url: https://github.com/PrefectHQ/prefect-openmetadata
theme:
  name: material
  palette:
    primary: blue
    accent: blue
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - prefect_openmetadata/
        - README.md

nav:
    - Home: index.md
    - Install OpenMetadata: install_openmetadata.md
    - Run ingestion flow: run_ingestion_flow.md
    - Schedule ingestion flow: schedule_ingestion_flow.md
    - Flow examples: flows.md
    - Ingestion workflow module: ingestion_workflow.md
